// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("1.4.1.0")]
[assembly: AssemblyInformationalVersionAttribute("1.4.1.0")]
[assembly: AssemblyFileVersionAttribute("1.4.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyVersion = "1.4.1.0";
        internal const System.String AssemblyInformationalVersion = "1.4.1.0";
        internal const System.String AssemblyFileVersion = "1.4.1.0";
    }
}
